# ############################################################################ #
#                                                                              #
#   Convert R Documentation to Markedly- (MyST) or reStructuredText (rST)      #
#                                                                              #
#   Copyleft (C) 2020-2021, Marek Gagolewski <https://www.gagolewski.com>      #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #


# Note: R Documentation HTML files are generated by a computer program.
# Hence, it is okay to process them with regexes.



html_process_manpage <- function(fhtml, bname, remove_code_link)
{
    stopifnot(stri_detect_regex(fhtml[6], "^<table.*</table>$"))

    stopifnot(stri_detect_regex(fhtml[8], "^<h2>.*</h2>$"))
    title <- stri_match_first_regex(fhtml[8], "^<h2>(.*)</h2>$")[, 2]


    fhtml[6] <- sprintf("<h1>%s: %s</h1>", bname, title)
    fhtml[8] <- ""



    # Remove link to the index page:
    stopifnot(stri_detect_fixed(fhtml[length(fhtml)-1], "00Index.html"))
    fhtml <- fhtml[-(length(fhtml)-1)]

    # Pandoc needs this to convert the links right:
    #    <code><a href="stri_datetime_add.html">stri_datetime_add</a>()</code>,
    # -> <a href="stri_datetime_add.html">stri_datetime_add()</a>,
    fhtml <- stri_replace_all_regex(
        fhtml,
        "<code><a href=\"([^./]+?\\.html)\">(.*?)</a>(.*?)</code>",
        if (remove_code_link) "<a href=\"$1\">$2$3</a>"
        else "<a href=\"$1\"><code>$2$3</code></a>"
    )


    # ../../base/html/xxx.html ->
    # https://stat.ethz.ch/R-manual/R-patched/library/base/html/xxx.html
    recommended_pkgs <- c("base", "boot", "class", "cluster", "codetools",
    "compiler", "datasets", "foreign", "graphics", "grDevices", "grid",
    "KernSmooth", "lattice", "MASS", "Matrix", "methods", "mgcv", "nlme",
    "nnet", "parallel", "rpart", "spatial", "splines", "stats", "stats4",
    "survival", "tcltk", "tools", "utils")

    fhtml <- stri_replace_all_regex(
        fhtml,
        sprintf(
            "<code><a href=\"\\.\\./\\.\\./(%s)/html/([^./]+?\\.html)\">(.*?)</a>(.*?)</code>",
            stri_flatten(recommended_pkgs, collapse="|")
        ),
        if (remove_code_link) "<a href=\"https://stat.ethz.ch/R-manual/R-patched/library/$1/html/$2\">$3$4</a>"
        else "<a href=\"https://stat.ethz.ch/R-manual/R-patched/library/$1/html/$2\"><code>$3$4</code></a>"
    )

    # ../../stringi/html/xxx.html ->
    # https://stringi.gagolewski.com/rapi/stri_info.html
    marek_pkgs <- c("stringi", "genieclust")

    fhtml <- stri_replace_all_regex(
        fhtml,
        sprintf(
            "<code><a href=\"\\.\\./\\.\\./(%s)/html/([^./]+?\\.html)\">(.*?)</a>(.*?)</code>",
            stri_flatten(marek_pkgs, collapse="|")
        ),
        if (remove_code_link) "<a href=\"https://$1.gagolewski.com/rapi/$2\">$3$4</a>"
        else "<a href=\"https://$1.gagolewski.com/rapi/$2\"><code>$3$4</code></a>"
    )

    fhtml <- stri_replace_all_regex(
        fhtml,
        "<pre>",
        "<pre class=\"r\">"
    )

    fhtml <- stri_replace_all_regex(fhtml, "^<h2>(.*)</h2>$", "<h1>$1</h1>")
    fhtml <- stri_replace_all_regex(fhtml, "^<h3>(.*)</h3>$", "<h2>$1</h2>")
    fhtml <- stri_replace_all_regex(fhtml, "^<h4>(.*)</h4>$", "<h3>$1</h3>")

    list(
        title=title,
        fhtml=fhtml
    )
}



rst_convert_manpage <- function(iname, oname)
{
    orst <- system2("pandoc", stdout=TRUE,
        args=c(
            "--from html",
            "--to rst",
            "--wrap=none",
            "--reference-links",
            iname
        ))
    # preformatted code blocks as R code
    orst <- stri_replace_first_regex(orst, "^::$", ".. code-block:: r")

    writeLines(orst, oname)
}


rst_generate_index <- function(package, output_dir, index)
{
    rapi_index_title <- sprintf("R Package *%s* Reference", package)
    rapi_index <- c(
        rapi_index_title,
        stri_dup("=", stri_length(rapi_index_title)),
        "",
        ".. toctree::",
        "    :maxdepth: 1",
        #"    :caption: API Documentation:",
        "",
        sprintf("    %s/%s", output_dir, index[, 1])
    )
    rapi_index
}



myst_convert_manpage <- function(iname, oname)
{
    orst <- system2("pandoc", stdout=TRUE,
        args=c(
            "--from html+tex_math_dollars",
            "--to markdown+backtick_code_blocks+tex_math_dollars-simple_tables-multiline_tables",
            "--atx-headers", #"--markdown-headings=atx",
            "--wrap=none",
#             "--indented-code-classes=r",
            #"--reference-links",
            iname
        ))
    # preformatted code blocks as R code
    orst <- stri_replace_first_regex(orst, "^``` \\{\\.r\\}$", "```r")

    writeLines(orst, oname)
}


myst_generate_index <- function(package, output_dir, index)
{
    rapi_index_title <- sprintf("R Package *%s* Reference", package)
    rapi_index <- c(
        rapi_index_title,
        stri_dup("=", stri_length(rapi_index_title)),
        "",
        "```{toctree}",
        ":maxdepth: 1",
        #"    :caption: API Documentation:",
        "",
        sprintf("%s/%s", output_dir, index[, 1]),
        "```"
    )
    rapi_index
}



package_process <- function(
    package, output_dir, index_file,
    output_ext, convert_manpage, generate_index,
    remove_code_link
)
{
    library(package, character.only=TRUE)
    input_path <- file.path(path.package(package), "html")

    if (!file.exists(file.path(input_path, "00Index.html"))) {
        stop(paste0("HTML documentation not installed. ",
            "Use `R CMD INSTALL <package_path> --html`."))
    }


    # Flush/recreate the output dir
    if (dir.exists(output_dir)) {
        unlink(output_dir, recursive=TRUE)
    }
    dir.create(output_dir)

    tmpname <- tempfile()

    # list of inputs:
    fnames <- setdiff(list.files(input_path, "\\.html$"), "00Index.html")

    # process all inputs:
    index <- character(0)
    for (fname in fnames) {
        cat(sprintf("Converting %s...", fname))
        bname <- stri_match_first_regex(fname, "(.*)\\.html")[, 2]

        page <- html_process_manpage(
            readLines(file.path(input_path, fname)),
            bname,
            remove_code_link
        )
        writeLines(page$fhtml, tmpname)

        convert_manpage(
            tmpname,
            sprintf(file.path(output_dir, "%s.%s"), bname, output_ext)
        )

        invisible(file.remove(tmpname))


        index <- rbind(index, c(bname, page$title))
        cat(" done.\n")

    }

    stopifnot(length(index) > 0)
    if (!is.matrix(index)) index <- matrix(index, nrow=1)

    writeLines(generate_index(package, output_dir, index), index_file)

    invisible(NULL)
}




#' @param package name of the package
#' @param output_dir target directory - will be wiped out
#' @param index_file filename with the function index toctree
Rd2rst <- function(package, output_dir="rapi", index_file="rapi.rst")
{
    package_process(
        package, output_dir, index_file,
        "rst", rst_convert_manpage, rst_generate_index,
        remove_code_link=TRUE
    )
}


#' @param package name of the package
#' @param output_dir target directory - will be wiped out
#' @param index_file filename with the function index toctree
Rd2myst <- function(package, output_dir="rapi", index_file="rapi.md")
{
    package_process(
        package, output_dir, index_file,
        "md", myst_convert_manpage, myst_generate_index,
        remove_code_link=FALSE
    )
}


