# ############################################################################ #
#                                                                              #
#   Converts an R package's documentation to reStructuredText (.rst)           #
#                                                                              #
#   Copyleft (C) 2020-2021, Marek Gagolewski <https://www.gagolewski.com>      #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #



# System requirements: R, pandoc

# Note: the HTML files are generated by a computer program.
# Hence, it is okay to process them with regexes.


# library("stringi")
# cat("Rd2rst - Copyleft (C) 2020-2021, Marek Gagolewski <https://www.gagolewski.com>\n")

# The function works in the current working directory. I'm that lazy. O_O


Rd2rst <- function(package) {
    library(package, character.only=TRUE)
    input_path <- file.path(path.package(package), "html")

    if (!file.exists(file.path(input_path, "00Index.html"))) {
        stop("HTML documentation not installed. Use `R CMD INSTALL <package_path> --html`.")
    }


    # Flush/recreate the output dir, which is rapi/
    if (dir.exists("rapi")) {
        unlink("rapi", recursive=TRUE)
    }
    dir.create("rapi")

    tmpname <- tempfile()

    # list of inputs:
    fnames <- setdiff(list.files(input_path, "\\.html$"), "00Index.html")

    # process all inputs:
    index <- character(0)
    for (fname in fnames) {
        cat(sprintf("Converting %s...", fname))
        fhtml <- readLines(file.path(input_path, fname))

        bname <- stri_match_first_regex(fname, "(.*)\\.html")[, 2]


        stopifnot(stri_detect_regex(fhtml[6], "^<table.*</table>$"))

        stopifnot(stri_detect_regex(fhtml[8], "^<h2>.*</h2>$"))
        title <- stri_match_first_regex(fhtml[8], "^<h2>(.*)</h2>$")[, 2]

        index <- rbind(index, c(bname, title))

        fhtml[6] <- sprintf("<h1>%s: %s</h1>", bname, title)
        fhtml[8] <- ""



        # Remove link to the index page:
        stopifnot(stri_detect_fixed(fhtml[length(fhtml)-1], "00Index.html"))
        fhtml <- fhtml[-(length(fhtml)-1)]

        # Pandoc needs this to convert the links right:
        #    <code><a href="stri_datetime_add.html">stri_datetime_add</a>()</code>,
        # -> <a href="stri_datetime_add.html">stri_datetime_add()</a>,
        fhtml <- stri_replace_all_regex(fhtml, "<code><a href=\"([^./]+?\\.html)\">(.*?)</a>(.*?)</code>", "<a href=\"$1\">$2$3</a>")

        writeLines(fhtml, tmpname)


        orst <- system2("pandoc", stdout=TRUE,
            args=c("--from html", "--to rst", "--wrap=none", tmpname))
        # preformatted code blocks as R code
        orst <- stri_replace_first_regex(orst, "^::$", ".. code-block:: r")

        oname <- sprintf("rapi/%s.rst", bname)
        writeLines(orst, oname)

        cat(" done.\n")

    }

    stopifnot(length(index) > 0)
    if (!is.matrix(index)) index <- matrix(index, nrow=1)


    rapi_index_title <- sprintf("R Package *%s* Reference", package)
    rapi_index <- c(
        rapi_index_title,
        stri_dup("=", stri_length(rapi_index_title)),
        "",
        ".. toctree::",
        "    :maxdepth: 1",
        #"    :caption: API Documentation:",
        "",
        sprintf("    rapi/%s", index[, 1])
    )
    writeLines(rapi_index, "rapi.rst")

    invisible(file.remove(tmpname))
    invisible(NULL)
}
